### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by Coda-Coda** [QBobWatson/ipe2tikz#10]
Hi, thank you for developing this tool. Could you please provide a license, ideally something permissive like MIT. Thanks.

**Comment by QBobWatson** [comment]
The TeX and lua files had a GPL license notice, but I failed to provide a copy of the GPL in the repository.  I've done that now.

I'm going to archive this repository as I'm no longer maintaining the software.  You're free to fork it and take over, of course!
