### ISSUE TITLE
texmf error: "Package tikz Error: I did not find the tikz library 'ipe'" (solved!)

### ISSUE THREAD

**Issue by pelegs** [QBobWatson/ipe2tikz#2]
On a Linux system (Ubuntu 17.10), I ran across the following problem:
when running via ipe, an error occurs: "Package tikz Error: I did not find the tikz library 'ipe'" (seems to be an issue with pdflatex/texmf).
I followed mvkorpel's answer here:
https://tex.stackexchange.com/questions/187193/how-to-install-tikz-pgf-libraries?rq=1
in short: if /home/[username]/texmf does not exist, run:
`mkdir -p ~/texmf/tex/generic/pgf`
and then create a subfolder "ipe" under pgf. Copy tikzlibraryipe.code.tex there, et viola!

**Comment by QBobWatson** [comment]
Thanks for the link!  I updated the readme.

I've always used TEXINPUTS, but the stackexchange solution is better.
