### ISSUE TITLE
Missing file 'tikzlibraryarrows.meta.code.tex'

### ISSUE THREAD

**Issue by Zuza** [QBobWatson/ipe2tikz#3]
While trying to run the ipelet I get that the file 'tikzlibraryarrows.meta.code.tex' is missing. Any idea on how can I install the library? Some Googling suggested that the problem might be the PGF 2.1 that comes with Ubuntu instead of PGF 3, but that would be strange given that I have a fresh and latest Ubuntu with all packages updated. Any suggestions are welcome.

Platform:
Ubuntu 18.04.1 LTS
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian)
tlmgr revision 46207 (2018-01-04 19:34:36 +0100)

**Comment by Zuza** [comment]
If anyone runs into the same problem: running "sudo tlmgr install pgf" will install the newer version of PGF with the correct library. Please ignore that "sudo tlmgr update -all" tells you that no packages have an available update.

**Comment by QBobWatson** [comment]
Thanks!  Yes, pgf-3 is a big update.
