### ISSUE TITLE
Core dump in Fedora 30

### ISSUE THREAD

**Issue by enriqueartal** [QBobWatson/ipe2tikz#4]
I used some time ago ipe2tikz with success, thanks for your work. I tried to use it recently but with any ipe file when I clicked in it the application is closed with a core dump.

**Comment by QBobWatson** [comment]
Still works on my side, ipe 7.2.9-1 on Ubuntu 19.04.  I don't have a Fedora machine running anywhere, so you'll have to give me more to go on.

**Comment by enriqueartal** [comment]
I attach the file with the details of the crash; ipe is version 7.2.12

[ipe-20190615-012419.kcrash.txt](https://github.com/QBobWatson/ipe2tikz/files/3292476/ipe-20190615-012419.kcrash.txt)

**Comment by grayswandyr** [comment]
Ipe 7.2.12 also crashes for me when exporting to a file (while exporting to a text object works). 
See [core.txt](https://github.com/QBobWatson/ipe2tikz/files/3414639/core.txt). Too bad 'cause this extension is so useful.

**Comment by fbob** [comment]
Same here on Ubuntu 19.04 with Ipe version 7.2.12
Yes it's too bad this extension was extremely useful ...

**Comment by QBobWatson** [comment]
I’ll update ipe and see if I can reproduce the issue.

**Comment by fbob** [comment]
Thanks :+1:

**Comment by QBobWatson** [comment]
Hopefully that did it.  Let me know if it works for you.

**Comment by grayswandyr** [comment]
It works on my PC, thanks.

**Comment by enriqueartal** [comment]
It works for me. Thanks!

**Comment by fbob** [comment]
Works like a charm.
You're ipelet really deserve the love you've given,
many many thanks :+1:

**Comment by QBobWatson** [comment]
I’m glad people are getting some use out of it!  I’ll go ahead and close the issue
