### ISSUE TITLE
ipe2tikz produces unreadable Ipe files

### ISSUE THREAD

**Issue by otfried** [QBobWatson/ipe2tikz#7]
ipe2tikz places objects in an invisible layer called `_TikZ replaced`.  If users make this layer visible, Ipe cannot read the file anymore, because spaces are not allowed in layer names.  (The problem is that the `view` element contains a space separated list of layers, so Ipe then starts looking for layers called `_TikZ` and `replaced`).

I suggest to use `_TikZ_replaced` instead.

See https://github.com/otfried/ipe-issues/issues/418

**Comment by QBobWatson** [comment]
Thanks for the tip!
